123
htmlacademy-htmlcss/1796901-gllacy-31 pull request #10
Opened 2021-06-22 17:22 UTC by Holder19

2021-06-22 19:14 UTC, Shramkoweb requested changes

2021-06-22 19:14 UTC, Shramkoweb commented on catalog.html
> +                  <a class="new-reg link" href="#">Новая регистрация</a>
`class="registration"` имхо этого достаточно)

2021-06-22 19:14 UTC, Shramkoweb commented on catalog.html
> +              <button class="btn btn-input" type="submit">Войти</button>
btn-input - а почему инпут?

2021-06-22 19:14 UTC, Shramkoweb commented on css/style.css
> +  grid-template-columns: 869px;
ой- то за размер)) Имхо можно по другому))

2021-06-23 17:51 UTC, Holder19 commented on catalog.html
> +              <button class="btn btn-input" type="submit">Войти</button>
ну она же для входа,вот я и подумал,что так неплохо будет)есть лучше вариант )?

2021-06-23 19:25 UTC, Shramkoweb commented on catalog.html
> +              <button class="btn btn-input" type="submit">Войти</button>
btn-login

2021-06-23 19:25 UTC, Shramkoweb commented on catalog.html
> +              <button class="btn btn-input" type="submit">Войти</button>
input - сразу имееться ввиду тег инпут, а не вход как действие

2021-06-23 19:26 UTC, Shramkoweb approved these changes

2021-06-23 19:26 UTC, merged