Верстка главной страницы
htmlacademy-htmlcss/1796901-gllacy-31 pull request #2
Opened 2021-05-22 13:32 UTC by Holder19

2021-05-22 18:47 UTC, Shramkoweb requested changes

2021-05-22 18:47 UTC, Shramkoweb commented on blank.html
> +</html>
В конце каждого файла стоит оставлять 1 пустую строчку, у тебя ее нет. Проверь что у тебя стоит плагин для editorconfig

2021-05-22 18:47 UTC, Shramkoweb commented on index.html
> +
Зачем тут пустая строчка?

2021-05-22 18:47 UTC, Shramkoweb commented on index.html
> +    <title>Магазин мороженного glaccy</title>
Вроде как имя Gllacy ?

2021-05-22 18:47 UTC, Shramkoweb commented on index.html
> +                </ul>
Внутри списка `ul` может быть только `li`

2021-05-22 18:47 UTC, Shramkoweb commented on index.html
> +            </ul>
```suggestion
            <ul>
                <li><a href="catalog.html">Каталог</a></li>
                <li>
                 <ul>
                    <li><span>Новинки</span></li>
                    <li><a href="catalog.html">Сливочное</a></li>
                    <li><a href="#">Щербеты</a></li>
                    <li><a href="#">Фруктовый лед</a></li>
                    <li><a href="#">Мелорин</a></li>
                </ul>
                </li>
     
```

2021-05-22 18:47 UTC, Shramkoweb commented on index.html
> +                <p>8 812 450-25-25</p>
Внутри списка не может быть детей кроме как `li`

2021-05-22 18:47 UTC, Shramkoweb commented on index.html
> +    <a href="#">Давайте оба!</a>
Почему это ссылка?

2021-05-22 18:47 UTC, Shramkoweb commented on index.html
> +    </ul>
Это слайдеР?

2021-05-22 18:47 UTC, Shramkoweb commented on index.html
> +        <p>При покупке 2 кг любого фруктового мороженого,<br>добавим в ваш заказ банку малинового варенья бесплатно.</p>
```suggestion
        <p>
          При покупке 2 кг любого фруктового мороженого,<br>добавим в ваш заказ банку малинового варенья бесплатно.
          </p>
```

2021-05-22 18:47 UTC, Shramkoweb commented on index.html
> +        <p>При покупке 2 кг любого фруктового мороженого,<br>добавим в ваш заказ банку малинового варенья бесплатно.</p>
Открытие и закрытие тегов на одном уровне - писал в чатике. Глянь

2021-05-22 18:47 UTC, Shramkoweb commented on index.html
> +                <p>310р/кг</p>
Может `span`  ?

2021-05-22 18:47 UTC, Shramkoweb commented on index.html
> +                <a href="#">Сливочное с апельсиновым <br>джемом и цитрусовой стружкой</a>
Очень много `br` -писал в чатике, текст можно переносить через CSS. 
Если, что пиши обсудим

2021-05-22 18:47 UTC, Shramkoweb commented on index.html
> +        </h2>
```suggestion
        <h2>
        Магазин Глэйси – это онлайн и офлайн-магазин по продаже мороженого собственного производства на развес
        </h2>
```

2021-05-22 18:47 UTC, Shramkoweb commented on index.html
> +                <p>Доставка нашего мороженого до заказчиков осуществляется в специальном термопаке, который не дает мороженому растаять в пути и позволяет сохранить превосходный вкус.
Форматирование

2021-05-22 18:47 UTC, Shramkoweb commented on index.html
> +        <p>Подпишитесь на нашу сладкую рассылку и будете всегда в курсе<br> всего самого вкусного, что у нас происходит. Обещаем не спамить<br> и не слать всякой не нужной ерунды. Честно =)</p>
Форматирование

2021-05-22 18:47 UTC, Shramkoweb commented on index.html
> +            <label for="email"></label>
Лейбл не может быть пустой

2021-05-22 18:47 UTC, Shramkoweb commented on index.html
> +            <h2>Создатели</h2>
Создатели - чего?

2021-05-22 18:47 UTC, Shramkoweb commented on index.html
> +                Сделано в <a href="#">HTML Academy</a>© 2021
Почитай критерии - там есть пункт куда должна вести эта ссылка

2021-05-22 18:47 UTC, Shramkoweb commented on index.html
> +        </form>
Форматирование

2021-05-22 18:47 UTC, Shramkoweb commented on index.html
> +            <p><label for="email">Логин</label>
for="email", а у инпута id id="login" - так не будет работать.

`for` будет искать `id` для инпута

2021-05-22 18:47 UTC, Shramkoweb commented on index.html
> +                <input type="password" id="login-password" name="password" placeholder="••••••••">
placeholder - что за интересный плейсхолдер такой?

2021-05-22 18:47 UTC, Shramkoweb commented on index.html
> +</html>
Не забудь добавить пустую стрчоку

2021-05-22 19:28 UTC, Holder19 commented on index.html
> +                <input type="password" id="login-password" name="password" placeholder="••••••••">
вхвхвх,это я спер с лайва из кода ,он мол там говорит ,в плейсхолдере должны быть точки,чтобы не видно было ,я не нашел символа и спер из кода лайваXD

2021-05-22 20:09 UTC, Holder19 commented on index.html
> +                <p>310р/кг</p>
я правильно понимаю,в span /кг ,

2021-05-22 20:09 UTC, Holder19 commented on index.html
> +            <h2>Создатели</h2>
тож решил по аналогии с лайвом сделать ,мол создатели проекта,а потом этот заголовок скрыть ,или он тут и не нужен?

2021-05-22 20:09 UTC, Holder19 commented on blank.html
> +</html>
Да ,не был установлен в принципе Editorconfig( немного не понял ,что значит после каждого файла нужно делать отступ 1 строчку?после каждого блока?или после каждого тега ?

2021-05-23 10:33 UTC, Shramkoweb commented on blank.html
> +</html>
Если ты ставишь плагин editorconfig он сам все сделает.

1 пустая строчка в конце каждого `ФАЙЛА`

2021-05-23 10:34 UTC, Shramkoweb commented on index.html
> +            </ul>
Да, не обернув этот список в элемент списка родителя `li`

2021-05-23 10:34 UTC, Shramkoweb commented on index.html
> +                <input type="password" id="login-password" name="password" placeholder="••••••••">
ой не )) Так не должно быть. 
Обычно это делают через JS меняю текст на точки, а точнее меняют тип инпута. Но это потом сможем обсудить

2021-05-23 10:46 UTC, Shramkoweb commented on index.html
> +                <p>310р/кг</p>
Нет все - имхо тут просто цена и не думаю, что это прям параграф текста

2021-05-23 10:46 UTC, Shramkoweb commented on index.html
> +            <h2>Создатели</h2>
Не нужен как по мне.

2021-05-23 11:23 UTC, Holder19 commented on index.html
> +
у меня vsc автоматически после сохранения ,делает отступ в некоторых местах ,и если я намеренно удаляю строку,сохраняю,он снова на том месте делает отступ

2021-05-23 11:32 UTC, Holder19 commented on index.html
> +                <input type="password" id="login-password" name="password" placeholder="••••••••">
вместо точек поставил placeholder="password"

2021-05-23 14:12 UTC, Shramkoweb commented on index.html
> +
Понял

2021-05-23 14:15 UTC, Shramkoweb approved these changes

2021-05-23 14:15 UTC, Shramkoweb commented on index.html
> +                        <li><span>Новинки</span></li>
`<li><a>Новинки</a></li>` у нас везде тут ссылки, для единообразия я бы оставил ссылку. Только без href

2021-05-23 14:15 UTC, Shramkoweb commented on index.html
> +            <p>
Выглядит так, как будто ты `p` используешь как обертку, чтобы сделать строки. Я бы использовал тут `div`

2021-05-23 14:15 UTC, merged

2021-05-23 14:38 UTC, Holder19 commented on index.html
> +            <p>
хорошо ,щас поменяю здесь,просто делал по аналогии с лайвом,изходя из того ,что рассказали,div на лайве не юзали,решил тоже так не делать