разметка каталога
htmlacademy-htmlcss/1796901-gllacy-31 pull request #3
Opened 2021-05-23 19:34 UTC by Holder19

2021-05-24 15:59 UTC, Shramkoweb requested changes

2021-05-24 15:59 UTC, Shramkoweb commented on catalog.html
> +
??

2021-05-24 15:59 UTC, Shramkoweb commented on catalog.html
> +                        <li><a href="catalog.html">Сливочное</a></li>
Мы уже на каталоге - зачем тут ссылка на самого себя?

2021-05-24 15:59 UTC, Shramkoweb commented on catalog.html
> +
Лишняя пустая строка?

2021-05-24 15:59 UTC, Shramkoweb commented on catalog.html
> +                <button>Оформить заказ</button>
Попап пока удалим - мы его потом будем делать

2021-05-24 15:59 UTC, Shramkoweb commented on catalog.html
> +        <nav>
Это не nav. Nav - это только главная навигация сайта, она у нас уже есть в header. 
Это просто ul внутри какого-то div

2021-05-24 15:59 UTC, Shramkoweb commented on catalog.html
> +        <nav>
https://htmlacademy.ru/courses/299/run/8

> Не каждая группа ссылок на странице должна быть обёрнута в <nav>. Например, небольшой блок со вспомогательными ссылками в подвале сайта. Такой блок внутри тега <footer> не нужно дополнительно оборачивать в тег <nav>.

2021-05-24 15:59 UTC, Shramkoweb commented on catalog.html
> +                    <p>Сортировка:</p>
Это `label` для нашего селекта

2021-05-24 15:59 UTC, Shramkoweb commented on catalog.html
> +                </select>
Форматирование поехало

2021-05-24 15:59 UTC, Shramkoweb commented on catalog.html
> +                <option value="popular">по популярности</option>
Этот пункт по дефолту чекнутый

2021-05-24 15:59 UTC, Shramkoweb commented on catalog.html
> +                    <p>Цена: 100 ₽ – 500 ₽</p>
Лейбл

2021-05-24 15:59 UTC, Shramkoweb commented on catalog.html
> +                    <ul>
Список тут лишний

2021-05-24 15:59 UTC, Shramkoweb commented on catalog.html
> +                            <input type="radio" value="fat-<10" name="fat-percents" id="fat-<10" checked>
fat-<10 - такой id сложно парсить потом на бекенде. 

У нас имя поля`fat-percents ` следовательно id могут быть просто 0, 10, 30, 30+

2021-05-24 15:59 UTC, Shramkoweb commented on catalog.html
> +                    <ul>
Список лишний

2021-05-24 15:59 UTC, Shramkoweb commented on catalog.html
> +                </li>
Форматирование

2021-05-24 15:59 UTC, Shramkoweb commented on catalog.html
> +                    <span>310р/кг</span>
```suggestion
                   <p>310<span>р/кг</span></p>
```

2021-05-24 15:59 UTC, Shramkoweb commented on catalog.html
> +                    <img src="https://via.placeholder.com/150x100" alt="назад">
Это не контент карти нка - а декоративные стрелочки. На будущее важно не забыть их убрать

2021-05-24 15:59 UTC, Shramkoweb commented on catalog.html
> +                    <img src="https://via.placeholder.com/150x100" alt="вперед">
Аналогично выше

2021-05-24 15:59 UTC, Shramkoweb commented on catalog.html
> +        <section>
div

2021-05-24 15:59 UTC, Shramkoweb commented on catalog.html
> +        <section>
div

2021-05-24 15:59 UTC, Shramkoweb commented on catalog.html
> +        <section>
div

2021-05-24 15:59 UTC, Shramkoweb commented on catalog.html
> +        <section>
ПОчему ты решил, что это секция?

2021-05-24 15:59 UTC, Shramkoweb commented on catalog.html
> +    <section>
Вроде как пока не надо делать

2021-05-25 17:26 UTC, Holder19 commented on catalog.html
> +                <button>Оформить заказ</button>
Совсем делитнуть ?или закоментить?

2021-05-25 18:06 UTC, Holder19 commented on catalog.html
> +                </select>
я не знаю почему,но я пытаюсь открывающий тег селект и закрывающий поставить на один уровень,чтобы было правильно ,а он при сохранении файла все равно ставить его в один уровень с опцией ,я вообще хз почему так

2021-05-25 18:20 UTC, Holder19 commented on catalog.html
> +        <section>
потому что нам так показали)а почему нет ?)

2021-05-25 18:28 UTC, Holder19 commented on catalog.html
> +        <section>
и это же точно такой footer как и на главной ,ты там про это ничего не написал

2021-05-25 18:30 UTC, Holder19 commented on catalog.html
> +                <button>Оформить заказ</button>
полностью удалить или закоментить?

2021-05-25 18:37 UTC, Holder19 commented on catalog.html
> +                    <ul>
я убрал ,но почему лишний?)

2021-05-25 18:43 UTC, Holder19 commented on catalog.html
> +                </li>
ты же про ценник ?

2021-05-25 18:44 UTC, Holder19 commented on catalog.html
> +                    <img src="https://via.placeholder.com/150x100" alt="назад">
я пока закоменчу их ,а потом поменяю

2021-05-25 18:45 UTC, Holder19 commented on catalog.html
> +    <section>
он тоже был на главной ,ты ничего не сказал)что делать ?

2021-05-25 20:26 UTC, Shramkoweb commented on catalog.html
> +                <button>Оформить заказ</button>
Закоментируй

2021-05-25 20:26 UTC, Shramkoweb commented on catalog.html
> +                </select>
Это prettier так ставит? Странно очень

2021-05-25 20:27 UTC, Shramkoweb commented on catalog.html
> +                    <ul>
Ну хз у нас есть филдсет - который говорит, что у меня набор инпутов. Как по мне этого достаточно, в документации не видел чтобы еще в список оборачивали

2021-05-25 20:28 UTC, Shramkoweb commented on catalog.html
> +                </li>
Тег картинки почему то на строчке с li.

2021-05-25 20:29 UTC, Shramkoweb commented on catalog.html
> +        <section>
Ага, я узнал, что вам такое показали - но да ладно)) На главной не писал, думал посомтреть, что ты сделаешь тут ))

2021-05-25 20:30 UTC, Shramkoweb commented on catalog.html
> +    <section>
Закоментируй.

Я просто решил не спешить и идти по плану академии)) Попапы будут потом))

2021-05-26 15:56 UTC, Holder19 commented on catalog.html
> +                    <span>310р/кг</span>
сделал как в примере учебника

2021-05-26 15:57 UTC, Holder19 commented on catalog.html
> +        <section>
ахахах,так как быть то лучше? оставить или заменить ?)

2021-05-26 16:00 UTC, Holder19 commented on catalog.html
> +        <section>
аналогично ситуации выше,как быть ,оставить или все же лучше заменить на див?)

2021-05-26 16:00 UTC, Holder19 commented on catalog.html
> +        <section>
аналогично выше,быть диву или не быть XD

2021-05-26 19:52 UTC, Shramkoweb commented on catalog.html
> +        <section>
Оставь

2021-05-26 19:53 UTC, Shramkoweb approved these changes

2021-05-26 19:53 UTC, merged