графика
htmlacademy-htmlcss/1796901-gllacy-31 pull request #4
Opened 2021-05-27 19:48 UTC by Holder19

2021-05-28 18:39 UTC, Shramkoweb reviewed
@Holder19 вижу ссылки на файлы, а сами файлы картинки где?? их нет в проекте

2021-05-28 18:39 UTC, Shramkoweb commented on catalog.html
> +                    <img src="/img/catalog-icecream/1.jpg" width="267" height="267" alt="Сливочное с апельсиновым джемом и цитрусовой стружкой" />
```suggestion
                    <img src="/img/catalog-ice-cream/1.jpg" width="267" height="267" alt="Сливочное с апельсиновым джемом и цитрусовой стружкой" />
```

2021-05-28 18:39 UTC, Shramkoweb commented on catalog.html
> +                    <img src="/img/catalog-icecream/10.jpg" width="267" height="267" alt="Сливочноe с ментоловым
Может лучше убрать папку `catalog-icecream` потому как в будущем сайте, могут эти картинки быть не только в каталоге.

А сами файлы именовать вот так `ice-cream-1. jpg ` `ice-cream-2 jpg `

2021-05-28 18:39 UTC, Shramkoweb commented on index.html
> +              <img src="/img/hit-icecream/Хит 1.jpg" width="267" height="267" alt="Сливочное с апельсиновым джемом и цитрусовой стружкой">
Не используй русские буквы в именах файлов/папок и так далее. Только латинские буквы

2021-05-28 18:39 UTC, Shramkoweb commented on index.html
> +              <img src="/img/hit-icecream/хит 3.jpg" width="267" height="267" alt="Сливочно-клубничное с присыпкой из белого шоколада">
Нельзя использовать пробелы в имени

2021-05-29 09:26 UTC, Holder19 commented on catalog.html
> +                    <img src="/img/catalog-icecream/10.jpg" width="267" height="267" alt="Сливочноe с ментоловым
они относятся в данном случае к сливочному мороженному,может папку так назвать?вместо каталог

2021-05-29 18:39 UTC, Shramkoweb commented on catalog.html
> +                    <img src="/img/catalog-icecream/10.jpg" width="267" height="267" alt="Сливочноe с ментоловым
можно и так)

2021-05-29 18:40 UTC, Shramkoweb requested changes

2021-05-29 18:40 UTC, Shramkoweb commented on catalog.html
> +                    <img src="/1796901-gllacy-31/img/creamy ice-cream/ice-cream-1.jpg" width="267" height="267" alt="Сливочное с апельсиновым джемом и цитрусовой стружкой" />
1796901 зачем это в имени?

2021-05-29 18:40 UTC, Shramkoweb commented on index.html
> +              <img src="/1796901-gllacy-31/img/hit-icecream/hit-4.jpg" width="267" height="267" alt="Сливочное крем-брюле с карамельной подливкой ">
Аа я понял, это ты прям имя папки проекта тут пишешь? Так не нужно делать.  
У вас была леккция про относительные и абсолютные пути?

2021-05-30 18:01 UTC, Shramkoweb approved these changes
Убери вот тут тире в начале имени `-ice-cream`

2021-05-30 18:01 UTC, merged