cтили1
htmlacademy-htmlcss/1796901-gllacy-31 pull request #5
Opened 2021-06-05 14:51 UTC by Holder19

2021-06-06 16:45 UTC, Shramkoweb requested changes

2021-06-06 16:45 UTC, Shramkoweb commented on css/style.css
> +
Одного отступа достаточно  )

2021-06-06 16:45 UTC, Shramkoweb commented on css/style.css
> +}
Отступ между селекторам
```suggestion
}

```

2021-06-06 16:45 UTC, Shramkoweb commented on css/style.css
> +  font-weight: bold;
А зачем по дефолту везде жирный текст?

2021-06-06 16:45 UTC, Shramkoweb commented on css/style.css
> +  text-transform: none;
зачем?

2021-06-06 16:45 UTC, Shramkoweb commented on css/style.css
> +}
```suggestion
.link-catalog:active {
  background: var(--special-link);
  box-shadow: inset 0px 2px 1px #696969;
  border-radius: 26px;
}
```

2021-06-06 16:45 UTC, Shramkoweb commented on css/style.css
> +}
Убирай личшние вложености селекторов, думаю и так должно работать?

2021-06-06 16:45 UTC, Shramkoweb commented on css/style.css
> +.dropdown .dropdown-title {
Убирай вложенности

2021-06-06 16:45 UTC, Shramkoweb commented on css/style.css
> +}
Отформатируй код - у тебя разные отступы везде

2021-06-06 16:45 UTC, Shramkoweb commented on css/style.css
> +}
```suggestion
.container > p {
  font-size: 60px;
  line-height: 60px;
  text-align: center;
}
```

2021-06-06 16:45 UTC, Shramkoweb commented on css/style.css
> +.container  .btn-1 {
```suggestion
.container .btn-1 {
```

2021-06-06 16:45 UTC, Shramkoweb commented on css/style.css
> +.container  .btn-1 {
btn-1 плохой класс, что значит `1` ?
Классы должны описывать суть елемента, что он значит.

2021-06-06 16:45 UTC, Shramkoweb commented on css/style.css
> +    linear-gradient(180deg, #f26843 0%, #e74a35 100%);
Что-то опять с форматирование - притиер ставил?

2021-06-06 16:45 UTC, Shramkoweb commented on css/style.css
> +.index-banner-1 .btn:hover {
Плохой класс опять с номером.

2021-06-06 16:45 UTC, Shramkoweb commented on css/style.css
> +  background-image: url(../img/background-images/raspberry-background.jpg);
```suggestion
  background-image: url("../img/background-images/raspberry-background.jpg");
```

2021-06-06 16:45 UTC, Shramkoweb commented on css/style.css
> +  background-image: url(../img/background-images/raspberry-background.jpg);
Не забывай кавычки для url

2021-06-06 16:45 UTC, Shramkoweb commented on css/style.css
> +.index-banner-2 .btn {
.btn  - это абстрактный класс для всех кнопок на сайте?

2021-06-06 16:45 UTC, Shramkoweb commented on css/style.css
> +.new-post p{
```suggestion
.new-post p {
```

2021-06-06 16:45 UTC, Shramkoweb commented on css/style.css
> +.new-post p{
Отступ перед кавычками

2021-06-06 16:45 UTC, Shramkoweb commented on css/style.css
> +}
```suggestion
.social-list ,
.info-list {
  list-style: none;
}
```

2021-06-06 16:45 UTC, Shramkoweb commented on css/style.css
> +  font-weight: bold;
у тебя шрифт и так на всем сайте тобой же был сделан ** bold** зачем тут опять ставить жирный?

2021-06-06 16:45 UTC, Shramkoweb commented on css/style.css
> +  border: 1px solid #D3D3D2;
Почему цвет не в переменной?

2021-06-06 16:45 UTC, Shramkoweb commented on css/style.css
> +  box-sizing: border-box;
box-sizing: border-box обычно ставиться для всего сайта

2021-06-06 16:45 UTC, Shramkoweb commented on css/style.css
> +
Лищная пустая строка

2021-06-06 18:57 UTC, Holder19 commented on css/style.css
> +  font-weight: bold;
я посмотрел макет,посмотрел текст,и вроде как жирного больше чем обычного и среднего ,или я ошибся)?

2021-06-06 18:59 UTC, Holder19 commented on css/style.css
> +  text-transform: none;
ты про высоту строки ,и тд?) я чет решил сделать как на лайве показали,для body прописать значения ,которых больше всего на макете

2021-06-06 19:09 UTC, Holder19 commented on css/style.css
> +.dropdown .dropdown-title {
если я убираю ,то здесь перестает работать ,не понимаю почему

2021-06-06 19:37 UTC, Holder19 commented on css/style.css
> +  box-sizing: border-box;
ох,не заметил ,если честно,я вообще это свойство случайно скопипастил с фигмы,когда копировал цвет фона)пока уберу вообще)

2021-06-07 19:11 UTC, Holder19 commented on css/style.css
> +.index-banner-2 .btn {
ага,не стоило так делать ?или все нормально ?

2021-06-08 18:46 UTC, Shramkoweb approved these changes

2021-06-08 18:46 UTC, Shramkoweb commented on index.html
> +    <section class="index-banner index-banner-chocolate">
👍

2021-06-08 18:46 UTC, merged