grid
htmlacademy-htmlcss/1796901-gllacy-31 pull request #7
Opened 2021-06-15 19:34 UTC by Holder19

2021-06-16 19:24 UTC, Shramkoweb requested changes

2021-06-16 19:24 UTC, Shramkoweb commented on catalog.html
> +              <a class="btn-social" href="https://www.facebook.com/htmlacademy">Фейсбук</a>
👍

2021-06-16 19:24 UTC, Shramkoweb commented on css/style.css
> +  align-content: start;
Вроде как это дефолтное значения и его можно не ставить? Проверь

2021-06-16 19:24 UTC, Shramkoweb commented on css/style.css
> +  width: 1146px;
Это точно тут нужно?? 100% не хватит ширины?

2021-06-17 17:27 UTC, Holder19 commented on css/style.css
> +  align-content: start;
вроде дефолтное stretch

2021-06-17 17:41 UTC, Holder19 commented on css/style.css
> +  width: 1146px;
если я задаю 100% то ширина получается 1193px,а по макету шапка 1146px;

2021-06-18 19:24 UTC, Shramkoweb commented on css/style.css
> +  align-content: start;
Согласен, попутал с justify-content

2021-06-18 19:25 UTC, Shramkoweb commented on css/style.css
> +  width: 1146px;
Я думаю надо смотреть почему она 1193px и искать проблему. А не давать жестко ширину, это на будущее будет лучше

2021-06-18 19:30 UTC, merged